In [1]:
import tensorflow as tf

In [9]:
import numpy as np

In [3]:
my_var = tf.Variable(tf.zeros([2,3]))

In [5]:
with tf.Session() as sess:
    initialize_op = tf.global_variables_initializer()
    sess.run(initialize_op)
    print(my_var)

Tensor("Variable/read:0", shape=(2, 3), dtype=float32)


In [6]:
x = tf.placeholder(tf.float32, shape=[2,2])

In [7]:
y = tf.identity(x)

In [10]:
x_vals = np.random.rand(2,2)

In [11]:
print(x_vals)

[[ 0.63904001  0.71757478]
 [ 0.67827946  0.0673739 ]]


In [12]:
with tf.Session() as sess:
    sess.run(y, feed_dict={x:x_vals})
    print(y)

Tensor("Identity:0", shape=(2, 2), dtype=float32)


In [13]:
first_var = tf.Variable(tf.zeros([2,3]))

In [14]:
with tf.Session() as sess:
    sess.run(first_var.initializer)
    second_var = tf.Variable(tf.zeros_like(first_var))
    sess.run(second_var.initializer)

In [15]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])

In [16]:
A = tf.truncated_normal([2, 3])

In [17]:
print(A)

Tensor("truncated_normal:0", shape=(2, 3), dtype=float32)


In [18]:
B = tf.fill([2,3], 5.0)

In [19]:
C = tf.random_uniform([3,2])

In [20]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))

In [23]:
with tf.Session() as sess:
    print(sess.run(identity_matrix))
    print(sess.run(A))
    print(sess.run(B))
    print(sess.run(C))
    print(sess.run(D))
    print(sess.run(C))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.46920019 -0.18776992 -0.34549198]
 [-0.42389634 -0.41273332 -0.33664918]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
[[ 0.43050516  0.86412501]
 [ 0.91338623  0.21248293]
 [ 0.36272669  0.5322665 ]]
[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]
[[ 0.66641653  0.43807709]
 [ 0.53849196  0.40213645]
 [ 0.34030628  0.6588105 ]]


In [32]:
with tf.Session() as sess:
    print(sess.run(A+B))
    print(sess.run(B-B))
    print(sess.run(tf.matmul(B, identity_matrix)))
    print(sess.run(tf.transpose(C)))
    print(sess.run(tf.matrix_determinant(D)))
    print(sess.run(tf.matrix_inverse(D)))

[[ 4.23163462  4.51592541  6.03695965]
 [ 4.78711319  6.23251295  6.0174408 ]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
[[ 0.42912006  0.72625363  0.308478  ]
 [ 0.46721041  0.34560776  0.12504137]]
-38.0
[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [36]:
with tf.Session() as sess:
    print(sess.run(tf.div(3, 4)))
    print(sess.run(tf.truediv(3, 4)))
    print(sess.run(tf.floordiv(3.0, 4.0)))
    print(sess.run(tf.div(3.0, 4.)))

0
0.75
0.0
0.75


In [39]:
with tf.Session() as sess:
    print(sess.run(tf.nn.relu([-3., 3., 10.])))
    print(sess.run(tf.nn.relu6([-3., 3, 10.])))
    print(sess.run(tf.nn.sigmoid([-3., 3., 10.])))

[  0.   3.  10.]
[ 0.  3.  6.]
[ 0.04742587  0.95257413  0.99995458]
